apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: braingeneers
  name: configmaps-power-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "update", "patch", "list", "delete", "watch"]
