apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: braingeneers
  name: jobs-power-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete"]
