apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: braingeneers
  name: pods-power-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/status", "pods/log"]
  verbs: ["get", "list", "watch"]
