apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nextflow-sa-role-binding-pvc
  namespace: braingeneers
subjects:
- kind: ServiceAccount
  name: nextflow-sa
  namespace: braingeneers
roleRef:
  kind: Role
  name: pvc-power-role
  apiGroup: rbac.authorization.k8s.io
